// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaxcrszofaapzzyzylfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVheGNyc3pvZmFhcHp6eXp5bGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTY3MzcsImV4cCI6MjA2ODk5MjczN30.YCLcjwiRiZ5PHzgBx5osqxHwyoALZU7j_-8LqNBZ7YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});